//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisOgloszen.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogloszenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogloszenie()
        {
            this.Wiadomosc = new HashSet<Wiadomosc>();
        }
    
        public long Id { get; set; }
        public string Tresc { get; set; }
        public long UzytkownikId { get; set; }
        public System.DateTime DataDodania { get; set; }
        public bool CzyUsuniete { get; set; }
        public string Temat { get; set; }
        public long KategoriaId { get; set; }
    
        public virtual Kategoria Kategoria { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wiadomosc> Wiadomosc { get; set; }
    }
}
