//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisOgloszen.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wiadomosc
    {
        public long Id { get; set; }
        public long WysylajacyUzytkownikId { get; set; }
        public System.DateTime DataDodania { get; set; }
        public string Tresc { get; set; }
        public long OdbierajacyUzytkownikId { get; set; }
        public long OgloszenieId { get; set; }
        public bool CzyOdczytano { get; set; }
    
        public virtual Ogloszenie Ogloszenie { get; set; }
        public virtual Uzytkownik UzytkownikWysylajacy { get; set; }
        public virtual Uzytkownik UzytkownikOdbierajacy { get; set; }
    }
}
